apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plugins.dapr.io
spec:
  group: dapr.io
  versions:
  - name: v1alpha1    
    schema:
      openAPIV3Schema:
        description: Plugin describes a Dapr plugin type
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: 
    storage: true
    served: true
    names:
      kind: Plugin
      plural: plugins
      singluar: plugin
      categories:
      - all
      - dapr
    scoped: Namespaced